version: 2.1
jobs:
  build:
    working_directory: ~/chameleon
    docker:
      - image: circleci/node:current-browsers
      - environment:
        TZ: "America/Chicago"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm config set prefix '~/.npm-global'
            yarn setup
      - run: # run tests
          name: Test
          command: yarn test
      - run: # run coverage report
          name: Code Coverage
          command: |
            yarn run generate-codecov
      - run:
          name: Build
          command: |
            yarn build:ci
